-- ============================================================
--  Campus Connect — Database Setup
--  Import this file via phpMyAdmin or run:
--  mysql -u root -p < campus_connect.sql
-- ============================================================

CREATE DATABASE IF NOT EXISTS campus_connect
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE campus_connect;

-- ── USERS TABLE ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS users (
  id          INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name        VARCHAR(120)  NOT NULL,
  email       VARCHAR(180)  NOT NULL UNIQUE,
  password    VARCHAR(255)  NOT NULL,          -- bcrypt hash
  strand      VARCHAR(80)   NOT NULL DEFAULT '',
  role        ENUM('admin','student') NOT NULL DEFAULT 'student',
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ── DEFAULT ADMIN ACCOUNT ────────────────────────────────────
-- Password: Admin@1234  (bcrypt hash generated by PHP)
INSERT INTO users (name, email, password, strand, role)
VALUES (
  'Administrator',
  'admin@campusconnect.com',
  '$2y$12$k9TF3cHJ2n5mWQ1vRfLkH.UlC7dZJ4nEXbmX7S2BqpT9U5yiKvDTq',
  'N/A',
  'admin'
);
