-- ============================================================
--  Campus Connect — Database Setup
--  Import this file via phpMyAdmin or run:
--  mysql -u root -p < campus_connectv2.sql
-- ============================================================

CREATE DATABASE IF NOT EXISTS campus_connectv2
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE campus_connectv2;

-- ── USERS TABLE ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS users (
  id          INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name        VARCHAR(120)  NOT NULL,
  email       VARCHAR(180)  NOT NULL UNIQUE,
  password    VARCHAR(255)  NOT NULL,          -- bcrypt hash
  strand      VARCHAR(80)   NOT NULL DEFAULT '',
  role        ENUM('admin','student') NOT NULL DEFAULT 'student',
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ── DEFAULT ADMIN ACCOUNT ────────────────────────────────────
-- Password: Admin@1234  (bcrypt hash generated by PHP)
INSERT INTO users (name, email, password, strand, role)
VALUES (
  'Administrator',
  'admin@campusconnect.com',
  '$2b$12$VKaQ4KuEma2oLTmvzC8UeOTQLfHKwdraUaNEL5PkarMLw3ukvtSx6',
  'N/A',
  'admin'
);

-- ── USER ACTIVITY / LOGIN LOG TABLE ──────────────────────────
CREATE TABLE IF NOT EXISTS user_logs (
  id         INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id    INT UNSIGNED NOT NULL,
  action     VARCHAR(50) NOT NULL DEFAULT 'login',  -- login | logout | signup
  logged_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Add last_seen column to users for active tracking
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_seen TIMESTAMP NULL DEFAULT NULL;
